# Generated by Django 3.2.7 on 2021-09-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('jan', models.BooleanField(default=False, verbose_name='Январь')),
                ('feb', models.BooleanField(default=False, verbose_name='Февраль')),
                ('mar', models.BooleanField(default=False, verbose_name='Март')),
                ('apr', models.BooleanField(default=False, verbose_name='Апрель')),
                ('may', models.BooleanField(default=False, verbose_name='Май')),
                ('jun', models.BooleanField(default=False, verbose_name='Июнь')),
                ('jul', models.BooleanField(default=False, verbose_name='Июль')),
                ('aug', models.BooleanField(default=False, verbose_name='Август')),
                ('sep', models.BooleanField(default=False, verbose_name='Сентябрь')),
                ('oct', models.BooleanField(default=False, verbose_name='Октябрь')),
                ('nov', models.BooleanField(default=False, verbose_name='Ноябрь')),
                ('dec', models.BooleanField(default=False, verbose_name='Декабрь')),
            ],
        ),
    ]
